name: CI Caller

on:
  push:
    branches:
      - main

jobs:
  
  call-reusable:
    uses: ./.github/workflows/resuable.yml
    environment: local
    with:
      branch: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}